### ISSUE TITLE
Add general GPU support

### ISSUE THREAD

**Issue by lamw** [maozdemir/privateGPT#2]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Is your feature request related to a problem? Please describe.**
It would be nice to have generalGPU support w/o forcing NVIDIA as the only option 

**Describe the solution you'd like**
I'm not sure if there's a way to do it generically and simply leverage the GPU within the system for processing or whether the GPU support relies on CUDA specifically

**Describe alternatives you've considered**
N/A

**Comment by maozdemir** [comment]
Hi, thanks for your suggestion. The main issue with this is I have no way of testing the implementation.
Also, another issue is this: [`NOTE: ROCm is not available on Windows`](https://pytorch.org/get-started/locally/)

I think I can use CLBlast, but it has several known issues on AMD platforms, and again, I can't test it. I'll look through and see if CLBlast implementation works on NVidia though.
